server:
    root: example
    server_name: johnnyserver.com 
    cgi_path: /usr/local/bin/python3
    client_max_body_size: 3000  
    error_page: 
        path: /errorPages/404.html
        status_code: 404
    listen:
        host: 127.0.0.1
        port: 8080
  location:
        route: /
        root: /alberto/
        index:  index.html
        autoindex: on
        allow_methods: GET
        cgi_ext: .php
    location: 
		route: /index/
        root: /
        autoindex: on 
        allow_methods: GET POST
        cgi_ext: .php
    location: 
		route: /tours/
        root: /tours/
        index: time.py
        autoindex: on 
        cgi_ext: .py
        allow_methods: GET POST
    location: 
		route: /test/
        root: /test/
        index: time.py
        autoindex: off 
        allow_methods: GET
  location: 
		route: /can-delete/
        root: /can-delete/
        autoindex: on 
        allow_methods: GET DELETE
    location: 
        allow_methods: GET
        route: /red/
        return: /tours/
server:
    root: example/host_tests/ 
    server_name: google.com
    listen:
        host: 127.0.0.1
        port: 8080
    location: 
		route: /
        root: /
        index:  index.html
        autoindex: off 
        allow_methods: GET
