server:
    root: ./example
    server_name: localhost
    cgi_path: /usr/bin/php
    client_max_body_size: 3000  
    error_page: 
        path: ./4xx.html
        status_code: 404
    listen:
        host: 127.0.0.1
        port: 8080
  location:
        route: /
        root: /alberto/
        index:  index.html
        autoindex: on
        allow_methods: GET POST
        cgi_ext: .php
    location: 
		route: /index/
        root: /
        autoindex: on 
        allow_methods: GET POST DELETE 
        cgi_ext: .php
    location: 
		route: /tours/
        root: /
        index: time.py
        autoindex: on 
        allow_methods: GET
    location: 
		route: /test/
        root: /test/
        index: time.py
        autoindex: off 
        allow_methods: GET
    location: 
        route: /red/
        return: /tours/
server:
    root:  docs/sweet_cake/
    server_name:  localhost
    cgi_path: /usr/bin/python3 /bin/bash
    client_max_body_size: 3000  
    error_page: 
        path: ./4xx.html
        status_code: 404
    listen:
        host: 127.0.0.1
        port: 8081
    location: 
		route: /test4
        root: ./
        index:  index2.html
        autoindex: off 
        allow_methods: GET POST 
        cgi_ext: .py    
    location: 
		route: /tours2
        root: ./
        index: time.py
        autoindex: off 
        allow_methods: GET
    location: 
        route: /red
        return: /tours        return: /tours
