server:
    root:  docs/fusion_web/
    name:  localhost
    cgi_path: /usr/bin/python3 /bin/bash
    client_max_body_size: 3000  
    error_page: 
        path: ./4xx.html
        status_code: 404
    listen:
        host: 127.0.0.0
        port: 8080
    location: 
		route: /test
        root: ./
        index:  index.html
        autoindex: off 
        allow_methods: GET POST DELETE 
        cgi_ext: .php    
    location: 
		route: /tours
        root: ./
        index: time.py
        autoindex: off 
        allow_methods: GET
    location: 
        route: /red
        root: ./
        return: /tours
server:
    root:
    name:  alberto
    cgi_path:   (11)
    client_max_body_size: 3000  (4)
    error_page:    (3)
        path:
        status_code:
    listen:       (1)
        host: 127.0.0.0
        port: 8080
    location:  
		route: 
        root:  
        index:  
        autoindex: off
        allow_methods: GET POST DELETE
        cgi_ext: .php     (11)
    location:   (5)
		route:  (5)
        root:   (8)
        index:  (10)
        autoindex: off   (9)
        allow_methods: GET  (6)
    location:   (5)
        route:  (5)
        root:   (8)
        return: /tours (7)