server:  (1)
    root:  (8)
    name:  (2)
    cgi_path:   (11)
    client_max_body_size: 3000  (4)
    error_page:    (3)
        path:
        status_code:
    listen:       (1)
        host: 127.0.0.0
        port: 8080
    location:   (5)
		route:  (5)
        root:   (8)
        index:  (10)
        autoindex: off   (9)
        allow_methods: GET POST DELETE   (6)
        cgi_ext: .php     (11)
    location:   (5)
		route:  (5)
        root:   (8)
        index:  (10)
        autoindex: off   (9)
        allow_methods: GET  (6)
    location:   (5)
        route:  (5)
        root:   (8)
        return: /tours (7)