server:
  root: example
  server_name: johnnyserver.com 
  cgi_path: /usr/local/bin/python3
  client_max_body_size: 3000000
  error_page: 
  path: /errorPages/404.html
  status_code: 404
  listen:
    host: 127.0.0.1
    port: 8080
  location:
    route: /
    root: /alberto/
    index:  index.html
    autoindex: on
    allow_methods: GET
    allow_uploads: on
    uploads_path: files/
    cgi_ext: .py
